__rethrow_casa_exceptions = True
context = h_init()
context.set_state('ProjectSummary', 'proposal_code', '2017.1.00293.S')
context.set_state('ProjectSummary', 'piname', 'unknown')
context.set_state('ProjectSummary', 'proposal_title', 'unknown')
context.set_state('ProjectStructure', 'ous_part_id', 'X1116534910')
context.set_state('ProjectStructure', 'ous_title', 'Undefined')
context.set_state('ProjectStructure', 'ppr_file', '/home/dared/opt/c5r1/mnt/dataproc/2017.1.00293.S_2017_11_29T13_39_34.232/SOUS_uid___A001_X1290_X4/GOUS_uid___A001_X1290_X5/MOUS_uid___A001_X1290_X6/working/PPR_uid___A001_X1290_X7.xml')
context.set_state('ProjectStructure', 'ps_entity_id', 'uid://A001/X1221/X236')
context.set_state('ProjectStructure', 'recipe_name', 'hifa_calimage')
context.set_state('ProjectStructure', 'ous_entity_id', 'uid://A001/X1221/X232')
context.set_state('ProjectStructure', 'ousstatus_entity_id', 'uid://A001/X1290/X6')
try:
    hifa_importdata(vis=['uid___A002_Xc56496_X1912', 'uid___A002_Xc5a30f_X8c3', 'uid___A002_Xc5b7d7_X870', 'uid___A002_Xc5b7d7_X492d', 'uid___A002_Xc5b7d7_X4cdb'], session=['session_1', 'session_4', 'session_6', 'session_7', 'session_7'])
    hifa_flagdata(pipelinemode="automatic")
    hifa_fluxcalflag(pipelinemode="automatic")
    hif_rawflagchans(pipelinemode="automatic")
    hif_refant(pipelinemode="automatic")
    h_tsyscal(pipelinemode="automatic")
    hifa_tsysflag(pipelinemode="automatic")
    hifa_antpos(pipelinemode="automatic")
    hifa_wvrgcalflag(pipelinemode="automatic")
    hif_lowgainflag(pipelinemode="automatic")
    hif_setmodels(pipelinemode="automatic")
    hifa_bandpassflag(pipelinemode="automatic")
    hifa_spwphaseup(pipelinemode="automatic")
    hifa_gfluxscaleflag(pipelinemode="automatic")
    hifa_gfluxscale(pipelinemode="automatic")
    hifa_timegaincal(pipelinemode="automatic")
    hif_applycal(pipelinemode="automatic")
    hifa_imageprecheck(pipelinemode="automatic")
    hif_makeimlist(intent='PHASE,BANDPASS,CHECK')
    hif_makeimages(pipelinemode="automatic")
    hif_checkproductsize(maxcubelimit=40.0, maxproductsize=400.0, maxcubesize=30.0)
    hifa_exportdata(pipelinemode="automatic")
finally:
    h_save()
